align.preset = none
assumeStandardLibraryStripMargin = true
docstrings.blankFirstLine = unfold
docstrings.wrap = keep
indent.caseSite = 2
indent.defnSite = 2
indent.extendSite = 2
lineEndings = unix
maxColumn = 110
project.git = true
runner.dialect = scala3
version = "3.11.1"
