/*
 * Copyright 2026 Viktor Rudebeck
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package jots

import cats.Hash
import cats.Show
import cats.syntax.all.*
import io.circe.Error
import io.circe.Json
import io.circe.JsonObject
import io.circe.jawn.JawnParser
import jots.JwtException.InvalidSignedJwtHeader
import scodec.bits.Bases.Alphabets.Base64UrlNoPad
import scodec.bits.ByteVector

/**
  * A [[JwtHeader]] together with its `String` representation.
  *
  * The `String` representation is either parsed or generated by
  * using e.g. [[JwtHeader#toSigned]]. Unlike [[JwtHeader]], the
  * [[SignedJwtHeader]] does not allow for modifications.
  *
  * The [[SignedJwtHeader]] should generally not be trusted unless
  * it is part of a [[VerifiedJwt]], so the signature is verified.
  */
sealed abstract class SignedJwtHeader {

  /**
    * Returns the header in its `String` representation.
    */
  def toBase64UrlNoPad: String

  /**
    * Returns a new [[JwtHeader]] using the signed header contents.
    *
    * This enables using a signed header as the basis of a new token.
    */
  def toHeader: JwtHeader

  /**
    * Returns the header represented as a `JsonObject`.
    */
  def toJsonObject: JsonObject

  /**
    * Returns the header represented as `Json`.
    */
  def toJson: Json

  /**
    * Alias for [[SignedJwtHeader#toBase64UrlNoPad]].
    */
  def show: String
}

object SignedJwtHeader {
  private final case class SignedJwtHeaderImpl(
    override val toJsonObject: JsonObject,
    override val toBase64UrlNoPad: String
  ) extends SignedJwtHeader {
    override def toHeader: JwtHeader =
      JwtHeader.fromJsonObject(toJsonObject)

    override def toJson: Json =
      toJsonObject.toJson

    override def toString: String =
      toJsonObject.toIterable
        .map { case (key, value) => show"$key -> $value" }
        .mkString("SignedJwtHeader(", ",", ")")

    override def show: String =
      toBase64UrlNoPad
  }

  /**
    * Alias for [[SignedJwtHeader.fromHeader]].
    */
  def apply(header: JwtHeader): SignedJwtHeader =
    fromHeader(header)

  /**
    * Returns a new [[SignedJwtHeader]] by parsing the specified
    * header in its `String` representation.
    */
  def fromBase64UrlNoPad(header: String): Either[JwtException, SignedJwtHeader] =
    for {
      bytes <- ByteVector
        .fromBase64Descriptive(header, Base64UrlNoPad)
        .leftMap(details => new InvalidSignedJwtHeader(s"failed to decode as Base64UrlNoPad: $details"))
      string <- bytes.decodeUtf8
        .leftMap(cause => new InvalidSignedJwtHeader("failed to decode as UTF-8", Some(cause)))
      jsonObject <- decode(string)
        .leftMap(cause => new InvalidSignedJwtHeader("failed to decode as JsonObject", Some(cause)))
      signed = new SignedJwtHeaderImpl(jsonObject, header)
    } yield signed

  /**
    * Returns a new [[SignedJwtHeader]] from the specified header.
    */
  def fromHeader(header: JwtHeader): SignedJwtHeader =
    new SignedJwtHeaderImpl(header.toJsonObject, header.toBase64UrlNoPad)

  /**
    * Alias for [[SignedJwtHeader.fromBase64UrlNoPad]],
    */
  def fromString(header: String): Either[JwtException, SignedJwtHeader] =
    fromBase64UrlNoPad(header)

  implicit val signedJwtHeaderHash: Hash[SignedJwtHeader] =
    Hash.fromUniversalHashCode

  implicit val signedJwtHeaderShow: Show[SignedJwtHeader] =
    Show.show(_.show)

  private val parser: JawnParser =
    JawnParser(allowDuplicateKeys = false)

  private def decode(s: String): Either[Error, JsonObject] =
    parser.decodeCharSequence[JsonObject](s)
}
