/*
 * Copyright 2026 Viktor Rudebeck
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package jots

import cats.Hash
import cats.Show
import cats.syntax.all.*
import io.circe.Error
import io.circe.Json
import io.circe.JsonObject
import io.circe.jawn.JawnParser
import jots.JwtException.InvalidSignedJwtClaims
import scodec.bits.Bases.Alphabets.Base64UrlNoPad
import scodec.bits.ByteVector

/**
  * A [[JwtClaims]] together with its `String` representation.
  *
  * The `String` representation is either parsed or generated by
  * using e.g. [[JwtClaims#toSigned]]. Unlike [[JwtClaims]], the
  * [[SignedJwtClaims]] does not allow for modifications.
  *
  * The [[SignedJwtClaims]] should generally not be trusted unless
  * it is part of a [[VerifiedJwt]], so the signature is verified.
  */
sealed abstract class SignedJwtClaims {

  /**
    * Returns the claims in its `String` representation.
    */
  def toBase64UrlNoPad: String

  /**
    * Returns a new [[JwtClaims]] using the signed claims content.
    *
    * This enables using signed claims as the basis of a new token.
    */
  def toClaims: JwtClaims

  /**
    * Returns the claims represented as a `JsonObject`.
    */
  def toJsonObject: JsonObject

  /**
    * Returns the claims represented as `Json`.
    */
  def toJson: Json

  /**
    * Alias for [[SignedJwtClaims#toBase64UrlNoPad]].
    */
  def show: String
}

object SignedJwtClaims {
  private final case class SignedJwtClaimsImpl(
    override val toJsonObject: JsonObject,
    override val toBase64UrlNoPad: String
  ) extends SignedJwtClaims {
    override def toClaims: JwtClaims =
      JwtClaims.fromJsonObject(toJsonObject)

    override def toJson: Json =
      toJsonObject.toJson

    override def toString: String =
      toJsonObject.toIterable
        .map { case (key, value) => show"$key -> $value" }
        .mkString("SignedJwtClaims(", ",", ")")

    override def show: String =
      toBase64UrlNoPad
  }

  /**
    * Alias for [[SignedJwtClaims.fromClaims]].
    */
  def apply(claims: JwtClaims): SignedJwtClaims =
    fromClaims(claims)

  /**
    * Returns a new [[SignedJwtClaims]] by parsing the specified
    * claims in its `String` representation.
    */
  def fromBase64UrlNoPad(claims: String): Either[JwtException, SignedJwtClaims] =
    for {
      bytes <- ByteVector
        .fromBase64Descriptive(claims, Base64UrlNoPad)
        .leftMap(details => new InvalidSignedJwtClaims(s"failed to decode as Base64UrlNoPad: $details"))
      string <- bytes.decodeUtf8
        .leftMap(cause => new InvalidSignedJwtClaims("failed to decode as UTF-8", Some(cause)))
      jsonObject <- decode(string)
        .leftMap(cause => new InvalidSignedJwtClaims("failed to decode as JsonObject", Some(cause)))
      signed = new SignedJwtClaimsImpl(jsonObject, claims)
    } yield signed

  /**
    * Returns a new [[SignedJwtClaims]] from the specified claims.
    */
  def fromClaims(claims: JwtClaims): SignedJwtClaims =
    new SignedJwtClaimsImpl(claims.toJsonObject, claims.toBase64UrlNoPad)

  /**
    * Alias for [[SignedJwtClaims.fromBase64UrlNoPad]],
    */
  def fromString(claims: String): Either[JwtException, SignedJwtClaims] =
    fromBase64UrlNoPad(claims)

  implicit val signedJwtClaimsHash: Hash[SignedJwtClaims] =
    Hash.fromUniversalHashCode

  implicit val signedJwtClaimsShow: Show[SignedJwtClaims] =
    Show.show(_.show)

  private val parser: JawnParser =
    JawnParser(allowDuplicateKeys = false)

  private def decode(s: String): Either[Error, JsonObject] =
    parser.decodeCharSequence[JsonObject](s)
}
